# .github/workflows/chromatic.yml

name: "Chromatic"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        # 以下にしたいがcacheをgit管理する必要がある。cacheファイルを指定する方法がわからないため保留
        # run: yarn install --immutable --immutable-cache --check-cache
        run: yarn install

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/componentLibrary
          exitZeroOnChanges: true